const socket = io();
const modal = document.getElementById('modal'), content = document.getElementById('modalContent');
const gameRoot = document.getElementById('gameRoot'), canvas = document.getElementById('gameCanvas'), ctx = canvas.getContext('2d');
const countdownEl = document.getElementById('countdown'), deathBanner = document.getElementById('deathBanner'), finishPanel = document.getElementById('finishPanel'), scoreboardEl = document.getElementById('scoreboard'), scoreRows = document.getElementById('scoreRows');
const timerEl = document.getElementById('timer'), healthFill = document.getElementById('healthFill'), healthText = document.getElementById('healthText'), weaponName = document.getElementById('weaponName'), ammoEl = document.getElementById('ammo'), reloadState = document.getElementById('reloadState'), powerState = document.getElementById('powerState'), hudScore = document.getElementById('hudScore');
const chars=['DHANVI','VEER','MAHAVEER','AGNIVEER','VANRAKSHAK','RAJVEER','SHARANG','KETU'];
let character='DHANVI', room=null, map=null, localId=socket.id, gameState=null, renderPlayers=new Map(), keys=new Set(), mouse={x:0,y:0,down:false}, camera={x:0,y:0}, scoreboardData=[];
const mobile={enabled:window.matchMedia('(pointer: coarse)').matches,moveX:0,moveY:0,aimX:1,aimY:0,fire:false};
const mobileControls=document.getElementById('mobileControls');
const imageCache={}; chars.forEach(c=>{const im=new Image();im.src=`/assets/warriors/${c.toLowerCase()}.png`;imageCache[c]=im});

const open=h=>{content.innerHTML=h;modal.classList.remove('hidden')};
document.getElementById('closeModal').onclick=()=>modal.classList.add('hidden');
modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};
const picker=()=>`<div class="char-grid">${chars.map(c=>`<button class="char-chip ${c===character?'selected':''}" data-char="${c}">${c}</button>`).join('')}</div>`;
function bind(){document.querySelectorAll('[data-char]').forEach(b=>b.onclick=()=>{character=b.dataset.char;document.querySelectorAll('[data-char]').forEach(x=>x.classList.toggle('selected',x.dataset.char===character))})}
function lobby(r){room=r;const a=r.adminId===socket.id;content.innerHTML=`<div class="eyebrow">ROOM LOBBY</div><h3>${r.name}</h3><div class="room-code">${r.code}</div><p class="hint">${r.visibility} · ${r.approval} · ${r.mode} · ${r.players.length}/${r.maxPlayers}</p><div class="lobby-list">${r.players.map(p=>`<div class="room-row"><div><strong>${p.isAdmin?'👑 ':''}${p.name}</strong><small>${p.character} · ${p.ready?'READY':'NOT READY'}</small></div>${a&&!p.isAdmin?`<button class="secondary kick" data-id="${p.id}">KICK</button>`:''}</div>`).join('')}</div>${a&&r.waiting.length?`<div class="eyebrow">WAITING FOR APPROVAL</div>${r.waiting.map(p=>`<div class="room-row"><div><strong>${p.name}</strong><small>${p.character}</small></div><div><button class="secondary approve" data-id="${p.id}">APPROVE</button> <button class="secondary reject" data-id="${p.id}">REJECT</button></div></div>`).join('')}`:''}${a?`<div class="actions"><button class="secondary" id="lock">${r.locked?'UNLOCK':'LOCK'} ROOM</button><button class="primary" id="start">START BATTLE →</button></div>`:''}<p class="hint">Server state: ${r.state}. Match: 5 min / 10 kills by default.</p>`;
content.querySelectorAll('.approve').forEach(b=>b.onclick=()=>socket.emit('room:approve',{playerId:b.dataset.id}));content.querySelectorAll('.reject').forEach(b=>b.onclick=()=>socket.emit('room:reject',{playerId:b.dataset.id}));content.querySelectorAll('.kick').forEach(b=>b.onclick=()=>socket.emit('room:kick',{playerId:b.dataset.id}));content.querySelector('#lock')?.addEventListener('click',()=>socket.emit('room:lock',{locked:!r.locked}));content.querySelector('#start')?.addEventListener('click',()=>socket.emit('room:start'))}

socket.on('room:update',lobby);socket.on('room:notice',x=>alert(x.message));socket.on('room:approved',()=>alert('Approved — welcome to the room.'));socket.on('room:rejected',x=>{alert(x.message);modal.classList.add('hidden')});socket.on('room:kicked',x=>{alert(x.message);gameRoot.classList.add('hidden');modal.classList.add('hidden')});socket.on('error:message',x=>alert(x.message));

socket.on('game:countdown',({seconds})=>{gameRoot.classList.remove('hidden');countdownEl.textContent=seconds;countdownEl.classList.remove('hidden');modal.classList.add('hidden');setTimeout(()=>countdownEl.classList.add('hidden'),850)});
socket.on('game:start',m=>{map=m;gameRoot.classList.remove('hidden');modal.classList.add('hidden');finishPanel.classList.add('hidden');deathBanner.classList.add('hidden');if(mobile.enabled)mobileControls.classList.remove('hidden');resize();});
socket.on('game:state',state=>{gameState=state;syncRenderPlayers(state.players);updateHUD(state)});
socket.on('game:score',data=>{scoreboardData=data;renderScoreboard(data)});
socket.on('game:damage',d=>{if(d.playerId===socket.id)flashDamage()});
socket.on('game:death',d=>{if(d.playerId===socket.id){deathBanner.classList.remove('hidden');setTimeout(()=>deathBanner.classList.add('hidden'),2100)}});
socket.on('game:respawn',d=>{if(d.playerId===socket.id)deathBanner.classList.add('hidden')});
socket.on('game:end',d=>{scoreboardData=d.scoreboard||[];renderScoreboard(scoreboardData);finishPanel.innerHTML=`<div class="eyebrow">BATTLE COMPLETE</div><h2>MATCH FINISHED</h2><div class="finish-table">${scoreboardData.map((p,i)=>`<div><span>${i+1}. ${p.name}</span><b>${p.kills} K / ${p.deaths} D · ${p.score}</b></div>`).join('')}</div><button class="primary" id="closeBattle">RETURN TO LOBBY</button>`;finishPanel.classList.remove('hidden');document.getElementById('closeBattle').onclick=()=>{finishPanel.classList.add('hidden');gameRoot.classList.add('hidden');if(room)lobby(room)};});

function syncRenderPlayers(players){const now=performance.now();const seen=new Set();for(const p of players){seen.add(p.id);let q=renderPlayers.get(p.id);if(!q){q={...p,rx:p.x,ry:p.y,tx:p.x,ty:p.y,last:now};renderPlayers.set(p.id,q)}q.tx=p.x;q.ty=p.y;q.vx=p.vx;q.vy=p.vy;q.aimX=p.aimX;q.aimY=p.aimY;q.health=p.health;q.maxHealth=p.maxHealth;q.alive=p.alive;q.weapon=p.weapon;q.ammo=p.ammo;q.maxAmmo=p.maxAmmo;q.reloading=p.reloading;q.powerReadyAt=p.powerReadyAt;q.blocking=p.blocking;q.powerName=p.powerName;q.name=p.name;q.character=p.character;q.kills=p.kills;q.deaths=p.deaths;q.score=p.score;q.last=now}for(const id of renderPlayers.keys())if(!seen.has(id))renderPlayers.delete(id)}
function updateHUD(s){const me=s.players.find(p=>p.id===socket.id);if(!me)return;const sec=Math.max(0,s.timeLeft||0);timerEl.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;healthFill.style.width=`${Math.max(0,me.health/me.maxHealth*100)}%`;healthText.textContent=`${Math.ceil(me.health)} / ${me.maxHealth}`;const weaponLabels={dhanush:'धनुष · DHANUSH',talwar:'तलवार · TALWAR',dhaal:'ढाल · DHAAL'};weaponName.textContent=weaponLabels[me.weapon]||me.weapon.toUpperCase();ammoEl.textContent=me.maxAmmo?`${me.ammo} / ${me.maxAmmo}`:'∞';reloadState.textContent=me.reloading?'DRAWING ARROWS…':(me.blocking?'KAVACH ACTIVE':'');const remain=Math.max(0,(me.powerReadyAt||0)-Date.now());powerState.textContent=remain>0?`POWER ${Math.ceil(remain/1000)}s`:`${me.powerName||'POWER'} READY`;hudScore.textContent=`${me.kills} KILLS · ${me.score} SCORE`;if(me.alive)deathBanner.classList.add('hidden')}
function renderScoreboard(data){scoreboardData=data||[];scoreRows.innerHTML=scoreboardData.map(p=>`<div class="score-row ${p.id===socket.id?'self':''}"><span>${p.name}</span><b>${p.kills}</b><b>${p.deaths}</b><b>${p.score}</b></div>`).join('')}
function flashDamage(){gameRoot.classList.add('damage-flash');setTimeout(()=>gameRoot.classList.remove('damage-flash'),120)}

function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
addEventListener('resize',resize);addEventListener('orientationchange',()=>setTimeout(resize,100));resize();
function worldMouse(){const rect=canvas.getBoundingClientRect();return {x:mouse.x-camera.x,y:mouse.y-camera.y}}
function mobileAimTarget(){const me=renderPlayers.get(socket.id);if(!me)return {x:camera.x+innerWidth/2,y:camera.y+innerHeight/2};return {x:me.rx+mobile.aimX*650,y:me.ry+mobile.aimY*650}}
function sendInput(){if(!gameState)return;const m=mobile.enabled?mobileAimTarget():worldMouse();const left=mobile.enabled?mobile.moveX<-.18:keys.has('a');const right=mobile.enabled?mobile.moveX>.18:keys.has('d');const down=mobile.enabled?mobile.moveY>.35:keys.has('s');socket.emit('player:input',{left,right,down,jump:false,fire:mobile.enabled?mobile.fire:mouse.down,aimX:m.x,aimY:m.y})}
setInterval(sendInput,50);

function setupVirtualStick(el,type){if(!el)return;let pointerId=null;const knob=el.querySelector('.stick-knob');const radius=el.clientWidth*.5-29;function update(e){const r=el.getBoundingClientRect();let dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2);const len=Math.hypot(dx,dy)||1;const scale=Math.min(1,radius/len);dx*=scale;dy*=scale;knob.style.transform=`translate(${dx}px,${dy}px)`;if(type==='move'){mobile.moveX=dx/radius;mobile.moveY=dy/radius}else{const len2=Math.hypot(dx,dy);if(len2>.12){mobile.aimX=dx/len2;mobile.aimY=dy/len2}}}function reset(){pointerId=null;knob.style.transform='translate(0,0)';if(type==='move'){mobile.moveX=0;mobile.moveY=0}}el.addEventListener('pointerdown',e=>{pointerId=e.pointerId;el.setPointerCapture(pointerId);update(e);e.preventDefault()});el.addEventListener('pointermove',e=>{if(e.pointerId===pointerId)update(e);e.preventDefault()});el.addEventListener('pointerup',e=>{if(e.pointerId===pointerId)reset()});el.addEventListener('pointercancel',reset)}
setupVirtualStick(document.getElementById('moveStick'),'move');setupVirtualStick(document.getElementById('aimStick'),'aim');
const bindTouch=(id,down,up)=>{const b=document.getElementById(id);if(!b)return;b.addEventListener('pointerdown',e=>{b.classList.add('active');down(e);e.preventDefault()});b.addEventListener('pointerup',e=>{b.classList.remove('active');up?.(e);e.preventDefault()});b.addEventListener('pointercancel',e=>{b.classList.remove('active');up?.(e)});};
bindTouch('fireBtn',()=>{mobile.fire=true;socket.emit('player:shoot')},()=>mobile.fire=false);
bindTouch('jumpBtn',()=>socket.emit('player:jump'));
bindTouch('reloadBtn',()=>socket.emit('player:reload'));
bindTouch('powerBtn',()=>socket.emit('player:power'));
bindTouch('weaponBtn',()=>{mobile.weaponIndex=(mobile.weaponIndex||1)%3+1;socket.emit('player:input',{weapon:['dhanush','talwar','dhaal'][mobile.weaponIndex-1]})});
addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();scoreboardEl.classList.remove('hidden');renderScoreboard(scoreboardData);return}if(e.key==='Escape'){scoreboardEl.classList.add('hidden');if(gameRoot.classList.contains('hidden'))return;modal.classList.remove('hidden');lobby(room);return}const k=e.key.toLowerCase();if(['w','a','s','d','q','r','1','2','3',' '].includes(k))e.preventDefault();if(k===' ')socket.emit('player:jump');else if(k==='q')socket.emit('player:power');else if(k==='r')socket.emit('player:reload');else if(k==='1')socket.emit('player:input',{weapon:'dhanush'});else if(k==='2')socket.emit('player:input',{weapon:'talwar'});else if(k==='3')socket.emit('player:input',{weapon:'dhaal'});else keys.add(k)});
addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase())});
addEventListener('keyup',e=>{if(e.key==='Tab')scoreboardEl.classList.add('hidden')});
canvas.addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY});canvas.addEventListener('mousedown',e=>{if(e.button===0){mouse.down=true;socket.emit('player:shoot')}});addEventListener('mouseup',e=>{if(e.button===0)mouse.down=false});

function draw(){requestAnimationFrame(draw);if(gameRoot.classList.contains('hidden')||!map)return;const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);const me=renderPlayers.get(socket.id);if(me){me.rx+=(me.tx-me.rx)*.25;me.ry+=(me.ty-me.ry)*.25;camera.x=clamp(me.rx-w*.42,0,map.width-w);camera.y=clamp(me.ry-h*.55,0,map.height-h)}ctx.save();ctx.translate(-camera.x,-camera.y);drawWorld();for(const p of renderPlayers.values()){p.rx+=(p.tx-p.rx)*.22;p.ry+=(p.ty-p.ry)*.22;if(p.alive)drawPlayer(p)}if(gameState?.projectiles)for(const b of gameState.projectiles){ctx.fillStyle=b.kind==='agni'?'#ef7d32':'#e8d09b';ctx.beginPath();ctx.arc(b.x,b.y,b.kind==='agni'?8:4,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff1b0';ctx.stroke();if(b.kind==='agni'){ctx.fillStyle='rgba(239,125,50,.18)';ctx.beginPath();ctx.arc(b.x,b.y,24,0,Math.PI*2);ctx.fill()}}ctx.restore();drawAim();}
function drawWorld(){const g=ctx.createLinearGradient(0,0,0,map.height);g.addColorStop(0,'#101a26');g.addColorStop(.55,'#2c2b24');g.addColorStop(1,'#15120f');ctx.fillStyle=g;ctx.fillRect(0,0,map.width,map.height);ctx.fillStyle='rgba(201,164,91,.18)';ctx.beginPath();ctx.arc(map.width/2,260,170,0,Math.PI*2);ctx.fill();for(let i=0;i<12;i++){ctx.fillStyle=i%2?'#202522':'#252820';ctx.fillRect(i*230,480-(i%3)*35,180,520)}ctx.fillStyle='#3a3026';for(const p of map.platforms){ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#6b5538';ctx.fillRect(p.x,p.y,p.w,8);ctx.fillStyle='#3a3026'}ctx.fillStyle='#6d5639';ctx.fillRect(0,map.groundY,map.width,map.height-map.groundY);ctx.fillStyle='#8a6b45';ctx.fillRect(0,map.groundY,map.width,8);}
function drawPlayer(p){const x=p.rx,y=p.ry;ctx.save();ctx.translate(x,y);const img=imageCache[p.character];if(img?.complete){ctx.globalAlpha=.92;ctx.drawImage(img,-50,-110,100,62);ctx.globalAlpha=1}else{ctx.fillStyle='#b28b4e';ctx.fillRect(-22,-46,44,90)}ctx.fillStyle='#050505aa';ctx.fillRect(-34,-58,68,6);ctx.fillStyle='#3c9a64';ctx.fillRect(-34,-58,68*Math.max(0,p.health/p.maxHealth),6);ctx.fillStyle='#eee8d8';ctx.font='bold 12px Arial';ctx.textAlign='center';ctx.fillText(p.name,0,-67);const ang=Math.atan2(p.aimY-y,p.aimX-x);ctx.rotate(ang);
  if(p.weapon==='dhanush'){ctx.strokeStyle='#c58f48';ctx.lineWidth=3;ctx.beginPath();ctx.arc(20,0,22,-1.05,1.05);ctx.stroke();ctx.strokeStyle='#e6d3a3';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(8,-19);ctx.lineTo(8,19);ctx.stroke();ctx.fillStyle='#c58f48';ctx.fillRect(7,-2,48,4);ctx.fillStyle='#ead7a2';ctx.beginPath();ctx.moveTo(55,0);ctx.lineTo(47,-5);ctx.lineTo(47,5);ctx.closePath();ctx.fill();}
  else if(p.weapon==='talwar'){ctx.strokeStyle='#e8d7b0';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(12,3);ctx.quadraticCurveTo(38,-13,58,-3);ctx.stroke();ctx.strokeStyle='#9b6b2f';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(10,-5);ctx.lineTo(18,8);ctx.stroke();}
  else {ctx.fillStyle='#9a6a2e';ctx.beginPath();ctx.arc(27,0,23,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#e0bd72';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#33271b';ctx.beginPath();ctx.arc(27,0,10,0,Math.PI*2);ctx.fill();}
  if(p.blocking){ctx.strokeStyle='#f3d07a';ctx.lineWidth=4;ctx.beginPath();ctx.arc(28,0,30,-1.1,1.1);ctx.stroke()}ctx.restore()}
function drawAim(){const me=renderPlayers.get(socket.id);if(!me)return;const sx=me.rx-camera.x,sy=me.ry-camera.y;ctx.save();ctx.strokeStyle='#d5b875aa';ctx.setLineDash([4,6]);ctx.beginPath();ctx.moveTo(sx,sy-35);ctx.lineTo(mouse.x,mouse.y);ctx.stroke();ctx.restore()}
draw();

document.getElementById('createBtn').onclick=()=>{open(`<div class="eyebrow">NEW BATTLE</div><h3>CREATE ROOM</h3><label>PLAYER NAME<input id="pn" maxlength="16" placeholder="Enter your name"></label><label>ROOM NAME<input id="rn" maxlength="24" value="KURUKSHETRA ROOM"></label><div class="grid2"><label>PLAYERS<select id="mp"><option>2</option><option>4</option><option selected>6</option><option>8</option></select></label><label>MODE<select id="mode"><option>Free For All</option><option>Team Battle</option><option>Single Player vs Bots</option></select></label></div><div class="grid2"><label>BOT DIFFICULTY<select id="bd"><option>Easy</option><option selected>Normal</option><option>Hard</option></select></label><label>VISIBILITY<select id="vis"><option>PRIVATE</option><option>PUBLIC</option></select></label><label>JOIN<select id="ap"><option>APPROVAL REQUIRED</option><option>OPEN</option></select></label></div><div class="grid2"><label>KILL TARGET<select id="kt"><option>10</option><option>15</option><option>20</option></select></label><label>MATCH MINUTES<select id="md"><option>5</option><option>10</option><option>15</option></select></label></div><div class="eyebrow">CHOOSE WARRIOR</div>${picker()}<button class="primary wide" id="create">CREATE ROOM →</button>`);bind();document.getElementById('create').onclick=()=>socket.emit('room:create',{playerName:document.getElementById('pn').value,name:document.getElementById('rn').value,maxPlayers:+document.getElementById('mp').value,mode:document.getElementById('mode').value,visibility:document.getElementById('vis').value,approval:document.getElementById('ap').value,botDifficulty:document.getElementById('bd').value,character,killTarget:+document.getElementById('kt').value,matchDuration:+document.getElementById('md').value*60},res=>{if(!res.ok)alert(res.error)})};
document.getElementById('joinBtn').onclick=()=>{open(`<div class="eyebrow">ENTER THE BATTLE</div><h3>JOIN ROOM</h3><label>PLAYER NAME<input id="jn" maxlength="16" placeholder="Enter your name"></label><label>ROOM CODE<input id="jc" maxlength="9" placeholder="KURU-4821"></label><div class="eyebrow">CHOOSE WARRIOR</div>${picker()}<button class="primary wide" id="join">JOIN →</button>`);bind();document.getElementById('join').onclick=()=>socket.emit('room:join',{code:document.getElementById('jc').value,playerName:document.getElementById('jn').value,character},res=>{if(!res.ok)alert(res.error);else if(!res.approved)content.innerHTML='<div class="eyebrow">REQUEST SENT</div><h3>WAITING FOR ADMIN</h3><p class="intro">Your request has been sent. Keep this window open.</p>'})};
document.getElementById('publicBtn').onclick=()=>{socket.emit('room:list');open('<div class="eyebrow">FIND A BATTLE</div><h3>PUBLIC ROOMS</h3><div id="publicList">Loading…</div>')};socket.on('public:rooms',rooms=>{const el=document.getElementById('publicList');if(!el)return;el.innerHTML=rooms.length?rooms.map(r=>`<div class="room-row"><div><strong>${r.name}</strong><small>${r.players}/${r.maxPlayers} · ${r.mode} · ${r.approval}</small></div><button class="secondary req" data-code="${r.code}">REQUEST</button></div>`).join(''):'<p class="hint">No public rooms available.</p>';el.querySelectorAll('.req').forEach(b=>b.onclick=()=>{document.getElementById('joinBtn').click();setTimeout(()=>document.getElementById('jc').value=b.dataset.code,50)})});
document.getElementById('settingsBtn').onclick=()=>open('<div class="eyebrow">CONFIGURE</div><h3>SETTINGS</h3><label>MASTER VOLUME<input type="range" min="0" max="100" value="80"></label><label>SFX VOLUME<input type="range" min="0" max="100" value="80"></label><label>MUSIC VOLUME<input type="range" min="0" max="100" value="60"></label><p class="hint">PC: WASD move · Mouse aim · LMB attack · Space jump · Q power · R draw arrows · 1/2/3 weapons · Tab scoreboard · Esc menu</p>');

